server:
  port: 8085

cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY:}
      secret-key: ${SECRET_KEY:}
    region: ap-south-1

application:
  bucket:
    name: 'albel-s3-document'

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      file-size-threshold: 10MB
      max-request-size: 10MB


